#!/bin/bash

WORKDIR=`pwd`
BASEDIR=$(readlink -f ${BASH_SOURCE[0]})
BASEDIR=$(dirname $BASEDIR)

clear
echo -e "\033[1;34m     _                                       "
echo " ___| |__   ___  _ ____      ____ _ _ __ ___ "
echo "/ __| '_ \ / _ \| '_ \ \ /\ / / _\` | '__/ _ \\"
echo "\__ \ | | | (_) | |_) \ V  V / (_| | | |  __/"
echo "|___/_| |_|\___/| .__/ \_/\_/ \__\_|_|  \___|"
echo "                |_|   # Project Updater v.1.1   "
echo "______________________________________________"
tput sgr0

# Helper method which creates a headline in the script
function create_headline {
    echo
    echo -e "\033[0;32m${1}"
    tput sgr0
}

# Helper method which creates an error output
function create_error {
    echo
    echo -e "\033[0;31m${1}"
    tput sgr0
}

if [ ! "$1" ]; then
	echo -en "Please provide your SW4 install dir (relative to this script): "
	read INSTALL

	APPPATH=${WORKDIR}/${INSTALL}
else
	APPPATH=${WORKDIR}/$1
fi


APPPATH=$(readlink -f ${APPPATH})

create_headline "[1.] Revert last changes"
cd ${APPPATH}

git reset --hard HEAD
git pull

cd ${APPPATH}

create_headline "[2.] Clear templates and database cache"
rm cache/templates/* -rf
rm cache/database/* -rf

rm -f cache/ClassMap_*.php

rm -rf cache/database/*
rm -rf cache/templates/cache/*
rm -rf cache/templates/compile/*

find cache/proxies/ -name '*.php' -print0 | xargs -0 rm -f
find cache/doctrine/filecache/ -name '*.php' -print0 | xargs -0 rm -f
find cache/doctrine/proxies/ -name '*.php' -print0 | xargs -0 rm -f
find cache/doctrine/attributes/ -name '*.php' -print0 | xargs -0 rm -f

create_headline "[4.] Set the correct permissions"
mkdir -p cache/templates/compile
chmod 777 cache/ -R
chmod 777 snippets/ -R

create_headline "[5.] Update database"
cd ${APPPATH}/build
ant build-database-deploy build-composer-install

echo ""
echo -en "\033[1;34m[SUCCESS] Project is up-to-date. Done at "
date +"%c"
tput sgr0
